import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1782639968255 implements MigrationInterface {
    name = 'InitialSchema1782639968255'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'bursar', 'teacher', 'parent')`);
        await queryRunner.query(`CREATE TYPE "public"."users_auth_provider_enum" AS ENUM('local', 'google')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'teacher', "auth_provider" "public"."users_auth_provider_enum" NOT NULL DEFAULT 'local', "google_id" character varying, "avatar_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "is_email_verified" boolean NOT NULL DEFAULT false, "phone_number" character varying, "refresh_token" character varying, "password_reset_token" character varying, "password_reset_expires" TIMESTAMP WITH TIME ZONE, "email_verification_token" character varying, "school_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users"  ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_25e1cf8f41bae2f3d11f3c2a02" ON "users"  ("school_id") `);
        await queryRunner.query(`CREATE TABLE "schools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "currency_code" character varying NOT NULL DEFAULT 'NGN', "admin_email" character varying NOT NULL, "logo_url" character varying, "address" character varying, "phone" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c3e2c029b71b41f671bfb3aa389" UNIQUE ("admin_email"), CONSTRAINT "PK_95b932e47ac129dd8e23a0db548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "school_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_81d53032048898783c180158880" UNIQUE ("name", "school_id"), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_398f3990f5da4a1efda173f576" ON "classes"  ("school_id") `);
        await queryRunner.query(`CREATE TYPE "public"."students_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."students_blood_group_enum" AS ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying NOT NULL, "middle_name" character varying, "last_name" character varying NOT NULL, "admission_number" character varying, "date_of_birth" date, "gender" "public"."students_gender_enum", "blood_group" "public"."students_blood_group_enum", "nationality" character varying, "state_of_origin" character varying, "religion" character varying, "photo_url" character varying, "address_line1" character varying, "address_line2" character varying, "city" character varying, "state" character varying, "country" character varying, "allergies" character varying, "medical_conditions" character varying, "emergency_contact" character varying, "parent_email" character varying NOT NULL, "parent_phone" character varying NOT NULL, "parent_name" character varying, "parent_relationship" character varying, "secondary_guardian_phone" character varying, "secondary_guardian_name" character varying, "admission_date" date, "previous_school" character varying, "school_id" uuid NOT NULL, "class_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa8edc7905ad764f8592456964" ON "students"  ("school_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_de6ad4ae6936dce474e2823984" ON "students"  ("class_id") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('present', 'absent', 'late')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "class_id" uuid NOT NULL, "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'present', "date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3a092b0d714a26c320100b4da7b" UNIQUE ("student_id", "class_id", "date"), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6200532f3ef99f639a27bdcae7" ON "attendance"  ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63ac3a881f4b1ff420942c217" ON "attendance"  ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff05fd5159e6d9d99514d46531" ON "attendance"  ("date") `);
        await queryRunner.query(`CREATE TABLE "dunning_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "days_before_exam" integer NOT NULL DEFAULT '14', "email_template" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d4349727bb16118b7b4f254199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97d8a856a4c69bb5afd588c46f" ON "dunning_configs"  ("school_id") `);
        await queryRunner.query(`CREATE TYPE "public"."fee_invoices_payment_status_enum" AS ENUM('defaulter', 'partially_paid', 'paid')`);
        await queryRunner.query(`CREATE TABLE "fee_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "school_id" uuid NOT NULL, "term_label" character varying NOT NULL, "total_amount" numeric(12,2) NOT NULL, "amount_paid" numeric(12,2) NOT NULL DEFAULT '0', "balance" numeric(12,2) NOT NULL DEFAULT '0', "payment_status" "public"."fee_invoices_payment_status_enum" NOT NULL DEFAULT 'defaulter', "line_items" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6916959219c76dfb86ecc822ab0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14b956ec2d4d139dcf692cf116" ON "fee_invoices"  ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_642401d8b025edcdd38eea9387" ON "fee_invoices"  ("school_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "receipt_number" character varying NOT NULL, "invoice_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "percentage_paid" numeric(5,2) NOT NULL, "balance_after" numeric(12,2) NOT NULL, "payment_method" character varying, "reference" character varying, "recorded_by" character varying, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a6659e5eb1bf3b467c819e7f167" UNIQUE ("receipt_number"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments"  ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "grading_schemes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "bands" jsonb NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "school_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e65d20cf390423cf178c627843e" UNIQUE ("school_id", "name"), CONSTRAINT "PK_819fba0aecafa18e58365143db3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a1c1adc9debc98a5de1f7c3637" ON "grading_schemes"  ("school_id") `);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "max_ca_score" integer NOT NULL DEFAULT '30', "max_exam_score" integer NOT NULL DEFAULT '70', "class_id" uuid NOT NULL, "school_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_275ac71cfea88470f4baae99c3" ON "subjects"  ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_07a82eb883094a6990b914cc15" ON "subjects"  ("school_id") `);
        await queryRunner.query(`CREATE TYPE "public"."scores_term_enum" AS ENUM('first', 'second', 'third')`);
        await queryRunner.query(`CREATE TABLE "scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "ca_score" numeric(5,2) NOT NULL DEFAULT '0', "exam_score" numeric(5,2) NOT NULL DEFAULT '0', "total_score" numeric(5,2) NOT NULL DEFAULT '0', "term" "public"."scores_term_enum" NOT NULL DEFAULT 'first', "academic_year" character varying NOT NULL, "grade" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f128701842913f174c39ca81169" UNIQUE ("student_id", "subject_id", "term", "academic_year"), CONSTRAINT "PK_c36917e6f26293b91d04b8fd521" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_45a2f5190af9a5e59f837e62d5" ON "scores"  ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f40b99b83783c6fff949f32ffc" ON "scores"  ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_91c8c6e767689ac83678e97e7a" ON "scores"  ("academic_year") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_term_enum" AS ENUM('first', 'second', 'third')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('draft', 'published')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "class_id" uuid NOT NULL, "term" "public"."reports_term_enum" NOT NULL, "academic_year" character varying NOT NULL, "average" numeric(5,2) NOT NULL DEFAULT '0', "position" integer, "teacher_comment" text, "conduct" integer, "punctuality" integer, "neatness" integer, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bde41ee8278c4dd11c9a847f4e3" UNIQUE ("student_id", "class_id", "term", "academic_year"), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b216cb73d9fbf2948c9e7d58f" ON "reports"  ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_162aa5a9843cff844c346b007d" ON "reports"  ("class_id") `);
        await queryRunner.query(`CREATE TABLE "staff_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "class_id" uuid NOT NULL, "is_class_teacher" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ea2a52768d0278ee785550505a2" UNIQUE ("user_id", "class_id"), CONSTRAINT "PK_ab013446523a48ceb9b14144530" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0278dc7c5fd965eecfac48f26b" ON "staff_assignments"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_13e70c915083e4e0e059c21dd8" ON "staff_assignments"  ("class_id") `);
        await queryRunner.query(`CREATE TYPE "public"."plans_billing_cycle_enum" AS ENUM('monthly', 'termly', 'annually')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "price_kobo" bigint NOT NULL DEFAULT '0', "billing_cycle" "public"."plans_billing_cycle_enum" NOT NULL DEFAULT 'monthly', "student_limit" integer, "staff_limit" integer, "features" jsonb NOT NULL DEFAULT '[]', "highlights" jsonb NOT NULL DEFAULT '[]', "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "is_custom" boolean NOT NULL DEFAULT false, "paystack_plan_code" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_253d25dae4c94ee913bc5ec4850" UNIQUE ("name"), CONSTRAINT "UQ_e7b71bb444e74ee067df057397e" UNIQUE ("slug"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('pending', 'active', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'pending', "paystack_reference" character varying, "paystack_transaction_id" character varying, "amount_paid_kobo" bigint NOT NULL DEFAULT '0', "starts_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_15c8dbbee08be9983adfaf7f3dd" UNIQUE ("paystack_reference"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c0bece3ccd5c6c711b30450ed9" ON "subscriptions"  ("school_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e45fca5d912c3a2fab512ac25d" ON "subscriptions"  ("plan_id") `);
        await queryRunner.query(`CREATE TABLE "staff_assignment_subjects" ("assignment_id" uuid NOT NULL, "subject_id" uuid NOT NULL, CONSTRAINT "PK_8896b18d63004f5b56f72254cd1" PRIMARY KEY ("assignment_id", "subject_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b93c4fd56b5a3231bb22dc5ffb" ON "staff_assignment_subjects"  ("assignment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae9d1cd74395ef91ec778e7d68" ON "staff_assignment_subjects"  ("subject_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_25e1cf8f41bae2f3d11f3c2a028" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_398f3990f5da4a1efda173f576f" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_aa8edc7905ad764f85924569647" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_de6ad4ae6936dce474e2823984e" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_6200532f3ef99f639a27bdcae7f" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_e63ac3a881f4b1ff420942c217a" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dunning_configs" ADD CONSTRAINT "FK_97d8a856a4c69bb5afd588c46f5" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_invoices" ADD CONSTRAINT "FK_14b956ec2d4d139dcf692cf116d" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_invoices" ADD CONSTRAINT "FK_642401d8b025edcdd38eea9387b" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "fee_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grading_schemes" ADD CONSTRAINT "FK_a1c1adc9debc98a5de1f7c36370" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_275ac71cfea88470f4baae99c36" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_07a82eb883094a6990b914cc15e" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_45a2f5190af9a5e59f837e62d52" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_f40b99b83783c6fff949f32ffc3" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_8b216cb73d9fbf2948c9e7d58fd" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_162aa5a9843cff844c346b007d9" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" ADD CONSTRAINT "FK_0278dc7c5fd965eecfac48f26b7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" ADD CONSTRAINT "FK_13e70c915083e4e0e059c21dd81" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_c0bece3ccd5c6c711b30450ed9a" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_assignment_subjects" ADD CONSTRAINT "FK_b93c4fd56b5a3231bb22dc5ffb3" FOREIGN KEY ("assignment_id") REFERENCES "staff_assignments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staff_assignment_subjects" ADD CONSTRAINT "FK_ae9d1cd74395ef91ec778e7d682" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staff_assignment_subjects" DROP CONSTRAINT "FK_ae9d1cd74395ef91ec778e7d682"`);
        await queryRunner.query(`ALTER TABLE "staff_assignment_subjects" DROP CONSTRAINT "FK_b93c4fd56b5a3231bb22dc5ffb3"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_c0bece3ccd5c6c711b30450ed9a"`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" DROP CONSTRAINT "FK_13e70c915083e4e0e059c21dd81"`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" DROP CONSTRAINT "FK_0278dc7c5fd965eecfac48f26b7"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_162aa5a9843cff844c346b007d9"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_8b216cb73d9fbf2948c9e7d58fd"`);
        await queryRunner.query(`ALTER TABLE "scores" DROP CONSTRAINT "FK_f40b99b83783c6fff949f32ffc3"`);
        await queryRunner.query(`ALTER TABLE "scores" DROP CONSTRAINT "FK_45a2f5190af9a5e59f837e62d52"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_07a82eb883094a6990b914cc15e"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_275ac71cfea88470f4baae99c36"`);
        await queryRunner.query(`ALTER TABLE "grading_schemes" DROP CONSTRAINT "FK_a1c1adc9debc98a5de1f7c36370"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "fee_invoices" DROP CONSTRAINT "FK_642401d8b025edcdd38eea9387b"`);
        await queryRunner.query(`ALTER TABLE "fee_invoices" DROP CONSTRAINT "FK_14b956ec2d4d139dcf692cf116d"`);
        await queryRunner.query(`ALTER TABLE "dunning_configs" DROP CONSTRAINT "FK_97d8a856a4c69bb5afd588c46f5"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_e63ac3a881f4b1ff420942c217a"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_6200532f3ef99f639a27bdcae7f"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_de6ad4ae6936dce474e2823984e"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_aa8edc7905ad764f85924569647"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_398f3990f5da4a1efda173f576f"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_25e1cf8f41bae2f3d11f3c2a028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae9d1cd74395ef91ec778e7d68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b93c4fd56b5a3231bb22dc5ffb"`);
        await queryRunner.query(`DROP TABLE "staff_assignment_subjects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e45fca5d912c3a2fab512ac25d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0bece3ccd5c6c711b30450ed9"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_billing_cycle_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13e70c915083e4e0e059c21dd8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0278dc7c5fd965eecfac48f26b"`);
        await queryRunner.query(`DROP TABLE "staff_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_162aa5a9843cff844c346b007d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b216cb73d9fbf2948c9e7d58f"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_term_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91c8c6e767689ac83678e97e7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f40b99b83783c6fff949f32ffc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45a2f5190af9a5e59f837e62d5"`);
        await queryRunner.query(`DROP TABLE "scores"`);
        await queryRunner.query(`DROP TYPE "public"."scores_term_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a82eb883094a6990b914cc15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_275ac71cfea88470f4baae99c3"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1c1adc9debc98a5de1f7c3637"`);
        await queryRunner.query(`DROP TABLE "grading_schemes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_642401d8b025edcdd38eea9387"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14b956ec2d4d139dcf692cf116"`);
        await queryRunner.query(`DROP TABLE "fee_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."fee_invoices_payment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97d8a856a4c69bb5afd588c46f"`);
        await queryRunner.query(`DROP TABLE "dunning_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff05fd5159e6d9d99514d46531"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63ac3a881f4b1ff420942c217"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6200532f3ef99f639a27bdcae7"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de6ad4ae6936dce474e2823984"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa8edc7905ad764f8592456964"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_blood_group_enum"`);
        await queryRunner.query(`DROP TYPE "public"."students_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_398f3990f5da4a1efda173f576"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "schools"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25e1cf8f41bae2f3d11f3c2a02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_auth_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
